Repository Permafrost-Game/Permafrost, pull requests merged in 2019-11, with the labels that each got.

#8 Pathfinder
  .vs/slnx.sqlite
  TeamProject/.vs/TeamProject/v15/Server/sqlite3/storage.ide
  TeamProject/.vs/TeamProject/v15/Server/sqlite3/storage.ide-shm
  TeamProject/.vs/TeamProject/v15/Server/sqlite3/storage.ide-wal
  TeamProject/Engine/Engine/ContentReader.cs
  TeamProject/Engine/Engine/Engine.csproj
  TeamProject/Engine/Engine/GameObject.cs
  TeamProject/Engine/Engine/IClickable.cs
  TeamProject/Engine/Engine/IDrawable.cs
  TeamProject/Engine/Engine/IUpdatable.cs
  TeamProject/Engine/Engine/PathFinding/PathFinder.cs
  TeamProject/Engine/Engine/PathFinding/PathFindingPathException.cs
  TeamProject/Engine/Engine/PathFinding/TileCosts.cs
  TeamProject/Engine/Engine/Sprite.cs
  TeamProject/Engine/Engine/TileGrid/Tile.cs
  TeamProject/Engine/Engine/TileGrid/TileMap.cs
  TeamProject/Engine/Engine/TileGrid/TileMapParser.cs
  TeamProject/Engine/Engine/TileGrid/TileSet.cs
  TeamProject/Engine/Engine/Zone.cs
  TeamProject/Engine/Engine/ZoneManager.cs
  TeamProject/GlobalWarmingGame/Content/Content.mgcb
  TeamProject/GlobalWarmingGame/Content/testmap.csv
  TeamProject/GlobalWarmingGame/Content/tileset/test_tileset-1/File.xml
  TeamProject/GlobalWarmingGame/Content/tileset/test_tileset-1/test_tile_set.tsx
  TeamProject/GlobalWarmingGame/Content/tileset/test_tileset-1/water.png
  TeamProject/GlobalWarmingGame/Game1.cs
  TeamProject/GlobalWarmingGame/GameObjectManager.cs
  TeamProject/GlobalWarmingGame/GlobalWarmingGame.csproj
  TeamProject/GlobalWarmingGame/MouseSelectionManager.cs
  TeamProject/GlobalWarmingGame/PathFindable.cs
Labels: feature

#18 Feature camera
  TeamProject/Engine/Engine/Camera.cs
  TeamProject/Engine/Engine/Engine.csproj
  TeamProject/Engine/Engine/Sprite.cs
  TeamProject/Engine/Engine/UI/Button.cs
  TeamProject/Engine/Engine/UI/DropdownMenu.cs
  TeamProject/GlobalWarmingGame/Action/Instruction.cs
  TeamProject/GlobalWarmingGame/Action/InstructionType.cs
  TeamProject/GlobalWarmingGame/Building.cs
  TeamProject/GlobalWarmingGame/Colonist.cs
  TeamProject/GlobalWarmingGame/Content/Colonist.png
  TeamProject/GlobalWarmingGame/Content/Content.mgcb
  TeamProject/GlobalWarmingGame/Content/farm.png
  TeamProject/GlobalWarmingGame/Content/testmap.csv
  TeamProject/GlobalWarmingGame/Game1.cs
  TeamProject/GlobalWarmingGame/GameObjectManager.cs
  TeamProject/GlobalWarmingGame/GlobalWarmingGame.csproj
  TeamProject/GlobalWarmingGame/MouseSelectionManager.cs
Labels: enhancement, feature

#21 UI and Instruction System
  TeamProject/Engine/Engine/Camera.cs
  TeamProject/Engine/Engine/ContentReader.cs
  TeamProject/Engine/Engine/Engine.csproj
  TeamProject/Engine/Engine/GameObject.cs
  TeamProject/Engine/Engine/IClickable.cs
  TeamProject/Engine/Engine/IUpdatable.cs
  TeamProject/Engine/Engine/Sprite.cs
  TeamProject/Engine/Engine/UI/Button.cs
  TeamProject/Engine/Engine/UI/DropdownMenu.cs
  TeamProject/GlobalWarmingGame/Action/Instruction.cs
  TeamProject/GlobalWarmingGame/Action/InstructionType.cs
  TeamProject/GlobalWarmingGame/Action/MouseInputMethod.cs
  TeamProject/GlobalWarmingGame/Action/SelectionInputMethod.cs
  TeamProject/GlobalWarmingGame/Action/SelectionManager.cs
  TeamProject/GlobalWarmingGame/Colonist.cs
  TeamProject/GlobalWarmingGame/Content/Content.mgcb
  TeamProject/GlobalWarmingGame/Content/berrybush.png
  TeamProject/GlobalWarmingGame/DisplayLabel.cs
  TeamProject/GlobalWarmingGame/Game1.cs
  TeamProject/GlobalWarmingGame/GameObjectManager.cs
  TeamProject/GlobalWarmingGame/GlobalWarmingGame.csproj
  TeamProject/GlobalWarmingGame/Interactions/Colonist.cs
  TeamProject/GlobalWarmingGame/Interactions/IInteractable.cs
  TeamProject/GlobalWarmingGame/Interactions/InteractableGameObject.cs
  TeamProject/GlobalWarmingGame/MouseSelectionManager.cs
  TeamProject/GlobalWarmingGame/PathFindable.cs
  TeamProject/GlobalWarmingGame/packages.config
  TeamProject/packages/Myra.0.9.6.184/.signature.p7s
  TeamProject/packages/Myra.0.9.6.184/Myra.0.9.6.184.nupkg
  TeamProject/packages/Myra.0.9.6.184/lib/net45/Myra.dll
  TeamProject/packages/Myra.0.9.6.184/lib/netstandard2.0/Myra.dll
Labels: enhancement, feature

#22 Fixed Camera Scaling origin
  TeamProject/Engine/Engine/Camera.cs
Labels: enhancement

#23 Added Passive Animals
  TeamProject/GlobalWarmingGame/Content/Rabbit.png
  TeamProject/GlobalWarmingGame/Game1.cs
  TeamProject/GlobalWarmingGame/GlobalWarmingGame.csproj
  TeamProject/GlobalWarmingGame/Interactions/Colonist.cs
  TeamProject/GlobalWarmingGame/Interactions/InteractableGameObject.cs
  TeamProject/GlobalWarmingGame/Interactions/PassiveMovingInteractable.cs
Labels: feature

#34 Feature instruction system
  TeamProject/Engine/Engine/Camera.cs
  TeamProject/GlobalWarmingGame/Action/Instruction.cs
  TeamProject/GlobalWarmingGame/Action/InstructionType.cs
  TeamProject/GlobalWarmingGame/Action/MouseInputMethod.cs
  TeamProject/GlobalWarmingGame/Content/Content.mgcb
  TeamProject/GlobalWarmingGame/Content/interactables/berrybush-harvestable.png
  TeamProject/GlobalWarmingGame/Content/interactables/berrybush-nonharvestable.png
  TeamProject/GlobalWarmingGame/Content/interactables/colonist.png
  TeamProject/GlobalWarmingGame/Content/interactables/farm.png
  TeamProject/GlobalWarmingGame/Content/interactables/rabbit.png
  TeamProject/GlobalWarmingGame/Game1.cs
  TeamProject/GlobalWarmingGame/GlobalWarmingGame.csproj
  TeamProject/GlobalWarmingGame/Interactions/InteractableGameObject.cs
  TeamProject/GlobalWarmingGame/Interactions/Interactables/Bush.cs
  TeamProject/GlobalWarmingGame/Interactions/Interactables/Colonist.cs
  TeamProject/GlobalWarmingGame/Interactions/Interactables/Farm.cs
  TeamProject/GlobalWarmingGame/Interactions/Interactables/Rabbit.cs
  TeamProject/GlobalWarmingGame/Interactions/PassiveMovingInteractable.cs
  TeamProject/GlobalWarmingGame/PathFindable.cs
Labels: enhancement, feature

#48 Menu System
  TeamProject/GlobalWarmingGame/Game1.cs
  TeamProject/GlobalWarmingGame/GlobalWarmingGame.csproj
  TeamProject/GlobalWarmingGame/MainMenu.cs
  TeamProject/GlobalWarmingGame/PauseMenu.cs
Labels: feature
